# Development overrides
# Locally copy or `ln -s` this file as compose.override.yml
version: "3"
services:
  cms:
    command: ["./docker-init.sh"]
    volumes:
      - ../bibdig-cms:/app
      - /app/node_modules
  ui:
    volumes:
      - ../bibdig-ui:/app
      - ~/.aws:/root/.aws
    environment:
      NODE_ENV: dev
