version: "3"
services:
  cms:
    build:
      context: ../bibdig-cms
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    depends_on:
      - database
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: database
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: example

  ui:
    build:
      context: ../bibdig-ui
      dockerfile: Dockerfile
    environment:
      NODE_ENV: prod
    depends_on:
      - cms

  web:
    build:
      context: ./web
    ports:
      - "80:80"
    depends_on:
      - ui

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: strapi
    volumes:
      - ../db_data:/var/lib/mysql
